### ISSUE TITLE
As a user I want the Linux release to have an exe file 

### ISSUE THREAD

**Issue by Nikolaj787** [ITU-BDSA2024-GROUP7/Chirp#42]
Change code in the YAML file to export an exe file for the Linux release, so that Linux users can run the program

Acceptance Criteria:
- Linux release has an exe file so Linux users can install and run the program

**Comment by DragonFlyersx** [comment]
This is only for legacy branch

**Comment by DragonFlyersx** [comment]
Change to a DLL file. Since linux and mac os runs on DLL files
